// SPDX-License-Identifier: LGPL-3.0-or-later
using OKF4net.Cli;

namespace OKF4net.Tests;

/// <summary>
/// Golden parity tests: every output the CLI produces is diffed byte-exact
/// against the corresponding output under <c>tests/fixtures/golden/</c>.
/// Provenance differs per golden: <c>validate.out</c> was regenerated by
/// running the OKF4net CLI itself against <c>tests/fixtures/appendix_a</c>
/// for the v0.1 → v0.2 spec bump (this project has deliberately detached
/// from Rust parity -- see <c>tests/fixtures/README.md</c>); <c>validate-v02.out</c>,
/// checked against the <c>tests/fixtures/okf_v02</c> bundle (see
/// <see cref="Validate_v02_fixture_matches_golden"/>), is a hand-authored
/// v0.2 fixture verified against the v0.2 spec text, since no reference
/// binary implements v0.2. <c>validate-computation.out</c> (see
/// <see cref="Validate_computation_fixture_matches_golden"/>), checked
/// against <c>tests/fixtures/okf_v02_computation</c>, is likewise a
/// hand-verified §10 Attested Computation / §6.2 fixture -- no reference
/// binary implements §10 either. Any divergence beyond the one documented
/// platform artifact (see <see cref="Validate_output_and_exitcode_match_golden"/>)
/// is a bug in the CLI, never a reason to touch a golden fixture.
/// </summary>
public class GoldenParityTests
{
    // `dotnet test` runs with the current directory set to the test
    // assembly's output folder (bin/Debug/net10.0), not the repo root, so
    // fixture paths are resolved relative to the repo root (located by
    // TestPaths.RepoRoot, walking up from the test assembly to the .sln).
    private static readonly string BundlePath = Path.Combine(TestPaths.RepoRoot(), "tests", "fixtures", "appendix_a");
    private static readonly string GoldenRoot = Path.Combine(TestPaths.RepoRoot(), "tests", "fixtures", "golden");

    private static string Golden(string rel) => File.ReadAllText(Path.Combine(GoldenRoot, rel));

    private static (int Code, string Out, string Err) Run(params string[] args) => TestPaths.Run(args);

    /// <summary>
    /// Runs <paramref name="action"/> with the process's current directory
    /// temporarily set to the repo root, restoring it afterward. Needed only
    /// by <c>validate</c>/<c>info</c>: their output embeds the bundle path
    /// exactly as given on the command line (<c>Bundle.Root</c>,
    /// <c>Diagnostic.Path</c>), and the goldens were captured by invoking the
    /// CLI from the repo root with the relative argument
    /// <c>tests/fixtures/appendix_a</c> -- reproducing that exact embedded
    /// string requires doing the same here. No other
    /// test in this assembly consults <see cref="Environment.CurrentDirectory"/>
    /// (all others resolve fixtures to absolute paths), and xunit runs the
    /// methods of a single class sequentially by default, so this is safe.
    /// </summary>
    private static T WithRepoRootAsCwd<T>(Func<T> action)
    {
        var original = Environment.CurrentDirectory;
        Environment.CurrentDirectory = TestPaths.RepoRoot();
        try
        {
            return action();
        }
        finally
        {
            Environment.CurrentDirectory = original;
        }
    }

    [Fact]
    public void Validate_output_and_exitcode_match_golden()
    {
        var r = WithRepoRootAsCwd(() => Run("validate", "tests/fixtures/appendix_a"));
        Assert.Equal(int.Parse(Golden("validate.exitcode")), r.Code);

        // The golden was captured on Linux, where paths display with '/'.
        // The per-file diagnostic paths are built by
        // combining the literal root "tests/fixtures/appendix_a" with
        // Path.Combine for every subsequent path component, and
        // Path.Combine emits the OS-native separator -- so on Windows the
        // tail of each path (everything past the root) comes out with '\'.
        // This is a platform display artifact, not a semantic difference,
        // so it alone is normalized in the C# OUTPUT (never the golden)
        // before comparing. Every other golden in this file is compared
        // strictly byte-for-byte with no normalization.
        var normalized = r.Out.Replace('\\', '/');
        Assert.Equal(Golden("validate.out"), normalized);
    }

    [Fact]
    public void Validate_v02_fixture_matches_golden()
    {
        var r = WithRepoRootAsCwd(() => Run("validate", "tests/fixtures/okf_v02"));
        Assert.Equal(int.Parse(Golden("validate-v02.exitcode")), r.Code);
        Assert.Equal(Golden("validate-v02.out"), r.Out.Replace('\\', '/'));
    }

    [Fact]
    public void Validate_computation_fixture_matches_golden()
    {
        var r = WithRepoRootAsCwd(() => Run("validate", "tests/fixtures/okf_v02_computation"));
        Assert.Equal(int.Parse(Golden("validate-computation.exitcode")), r.Code);
        Assert.Equal(Golden("validate-computation.out"), r.Out.Replace('\\', '/'));
    }

    [Fact]
    public void Validate_reserved_fixture_matches_golden()
    {
        var r = WithRepoRootAsCwd(() => Run("validate", "tests/fixtures/okf_v02_reserved"));
        Assert.Equal(int.Parse(Golden("validate-reserved.exitcode")), r.Code);
        Assert.Equal(Golden("validate-reserved.out"), r.Out.Replace('\\', '/'));
    }

    [Fact]
    public void Info_output_matches_golden()
    {
        var r = WithRepoRootAsCwd(() => Run("info", "tests/fixtures/appendix_a"));
        Assert.Equal(0, r.Code);
        Assert.Equal(Golden("info.out"), r.Out);
    }

    [Fact]
    public void Graph_dot_matches_golden()
    {
        // Concept ids -- and therefore every string `graph --dot` prints --
        // are always normalized to '/' by ConceptId.FromPath regardless of
        // the bundle root's path style, so the absolute Windows BundlePath
        // is safe here: no separator artifact, no repo-root CWD dance
        // needed, and the comparison below is strict byte-for-byte.
        var r = Run("graph", BundlePath, "--dot");
        Assert.Equal(0, r.Code);
        Assert.Equal(Golden("graph.dot"), r.Out);
    }

    [Fact]
    public void Fmt_output_matches_golden()
    {
        var r = Run("fmt", Path.Combine(BundlePath, "tables", "users.md"));
        Assert.Equal(0, r.Code);
        Assert.Equal(Golden(Path.Combine("fmt", "users.md")), r.Out);
    }

    [Fact]
    public void Index_generation_matches_golden()
    {
        using var tmp = new TempDir();
        CopyDirectory(BundlePath, tmp.Path);

        var written = IndexGenerator.RegenerateIndexes(tmp.Path);
        Assert.Equal(3, written.Count);

        var generatedIndexFiles = Directory.GetFiles(tmp.Path, "index.md", SearchOption.AllDirectories);
        Assert.Equal(3, generatedIndexFiles.Length);

        string[] relIndexPaths =
        [
            "index.md",
            Path.Combine("datasets", "index.md"),
            Path.Combine("tables", "index.md"),
        ];
        foreach (var rel in relIndexPaths)
        {
            var actual = File.ReadAllText(Path.Combine(tmp.Path, rel));
            var expected = Golden(Path.Combine("index-input", rel));
            Assert.Equal(expected, actual);
        }

        // Exactly the 3 generated index.md files plus the 5 original
        // source documents copied in -- no extras.
        var allFiles = Directory.GetFiles(tmp.Path, "*", SearchOption.AllDirectories);
        Assert.Equal(8, allFiles.Length);
    }

    private static void CopyDirectory(string sourceDir, string destDir)
    {
        Directory.CreateDirectory(destDir);
        foreach (var file in Directory.GetFiles(sourceDir))
        {
            File.Copy(file, Path.Combine(destDir, Path.GetFileName(file)));
        }

        foreach (var dir in Directory.GetDirectories(sourceDir))
        {
            CopyDirectory(dir, Path.Combine(destDir, Path.GetFileName(dir)));
        }
    }
}
